[tool.poetry]
name = "software"
version = "0.1.0"
description = ""
authors = ["Dora <smallyo2000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyserial = "^3.5"
pyqt5 = "^5.15.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
